[package]
name = "rabbit"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.6"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.6.1", features = ["fs"] }
walkdir = "2.5.0"
zip = "2.2.0"
